// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nclpyhazbyqftcwhxqfz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jbHB5aGF6YnlxZnRjd2h4cWZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMTI2NjcsImV4cCI6MjA2MjY4ODY2N30.axPglYDOA-Y6CJigJc9w1I5NJ0cSIYTiUcngmrHzync";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);